### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by liufy11** [danwkenn/SimAdmixtR#1]
can you tell me how to install SimAdmixtR ? I try to install it by using install.packages("SimAdmixtR") under R environment or using Rstudio to install locally after download from github. but both ways failed

**Comment by danwkenn** [comment]
Thanks for your interest in our package! You will need use `devtools::install_github("danwkenn/SimAdmixtR")`. 
The reason for this that `install.packages()` only works for CRAN packages. If you would like to install from local you can download the package and run `devtools::install_local("/path/to/SimAdmixtR")`

**Comment by liufy11** [comment]
Thanks for your reply, I install SimAdmixR successfully using&nbsp;&nbsp;devtools::install_local("/path/to/SimAdmixtR")&nbsp;
but when I use the function stitch &nbsp;in&nbsp;SimAdmixR&nbsp;, It says&nbsp;could not find function "stitch", &nbsp;and the same questions happened to other functions.
when I install&nbsp;SimAdmixR&nbsp;and then library(SimAdmixtR), It shows no error. &nbsp;After I input&nbsp;help(package="SimAdmixtR"), It shows me the usage of&nbsp;&nbsp;SimAdmixR. and when I input ?stitch It also shows me the usage of stitch. So I think there's no problem in installation.
I use stitch according to the examples in the document,&nbsp;
&gt; listA = list(1,2,3,4)
&gt; listB = list("A","B","C","D")
&gt; stitch(listA,listB)
and then ,the screen says
Error in stitch(listA, listB) : could not find function "stitch"
Do you know where is wrong or what should I do ?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel Kennedy"<notifications@github.com&gt;;e
发送时间:&nbsp;2020年5月21日(星期四) 上午8:43
收件人:&nbsp;"danwkenn/SimAdmixtR"<SimAdmixtR@noreply.github.com&gt;;
抄送:&nbsp;"fangying"<365698105@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [danwkenn/SimAdmixtR] How to install ? (#1)





 
Thanks for your interest in our package! You will need use devtools::install_github("danwkenn/SimAdmixtR").
 The reason for this that install.packages() only works for CRAN packages. If you would like to install from local you can download the package and run devtools::install_local("/path/to/SimAdmixtR")

**Comment by danwkenn** [comment]
There was an error in the code, thank you for posting your issue. I have now updated the code. You can reinstall in a fresh workspace with:
`devtools::install_github("danwkenn/SimAdmixtR",force = TRUE)`
or if doing from local, redownload the repo and run:
`devtools::install_local("/path/to/SimAdmixtR",force = TRUE)`

**Comment by liufy11** [comment]
both ways faild
from github:
devtools::install_github("danwkenn/SimAdmixtR",force = TRUE)
Downloading GitHub repo danwkenn/SimAdmixtR@master
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: /bin/gtar: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
sh: /bin/gtar: No such file or directory
Error: Failed to install 'SimAdmixtR' from GitHub:
&nbsp; error in running command
In addition: Warning message:
In utils::untar(tarfile, ...) :
&nbsp; ?.bin/gzip -dc '/tmp/Rtmpe7rTbl/file47ef5ff53299.tar.gz' | /bin/gtar -xf '-' -C '/tmp/Rtmpe7rTbl/remotes47ef51b5f4d'?.returned&nbsp;
error code 127



locally
download from&nbsp;git@github.com:danwkenn/SimAdmixtR.git again
&gt; devtools::install_local("~/Admix/Sim/SimAdmixtR-master.zip",force = TRUE)
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: Failed to install 'SimAdmixtR-master.zip' from local:
&nbsp; character argument expecteda











------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Daniel Kennedy"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 中午1:26
收件人:&nbsp;"danwkenn/SimAdmixtR"<SimAdmixtR@noreply.github.com&gt;;
抄送:&nbsp;"fangying"<365698105@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [danwkenn/SimAdmixtR] How to install ? (#1)





 
There was an error in the code, thank you for posting your issue. I have now updated the code. You can reinstall in a fresh workspace with:
 devtools::install_github("danwkenn/SimAdmixtR",force = TRUE)
 or if doing from local, redownload the repo and run:
 devtools::install_local("/path/to/SimAdmixtR",force = TRUE)

**Comment by danwkenn** [comment]
The error below:
`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory`
suggests that your current working directory has been moved or deleted. I suggest that you need to start a new instance of Rstudio with a clean workspace, verify that the current working directory exists, and try one of the install methods.
Also I neglected to say that for local install I believe you need to unzip the folder first, however you will need solve the above error first.

**Comment by danwkenn** [comment]
Have checked package installs via the `install_github()` method, and functions are correctly exporting, so will close this issue if there are no other problems.
